# -*- coding: utf-8 -*-
"""math_function

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dVCH89bVNT9WAlGaZzsC5GRgifDnWE0A
"""

def add(a, b):
    return a + b